spring:
 datasource: 
  url: jdbc:mysql://localhost:3306/cloudinary
  username: springstudent
  password: springstudent
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 servlet:
  multipart:
   max-file-size: 50MB
   max-request-size: 50MB

cloudinary:
 cloud-name: 
 api-key: 
 api-secret: 
 

    